{
    "title": "Avatar: The Way of Water",
    "year": 2022,
    "ids": {
        "trakt": 56580,
        "slug": "avatar-the-way-of-water-2022",
        "imdb": "tt1630029",
        "tmdb": 76600,
    },
    "tagline": "Return to Pandora.",
    "overview": "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    "released": "2022-12-16",
    "runtime": 192,
    "country": "us",
    "trailer": "https://youtube.com/watch?v=o5F8MOz_IDw",
    "homepage": "https://www.avatar.com/movies/avatar-the-way-of-water",
    "status": "released",
    "rating": 7.75254,
    "votes": 10034,
    "comment_count": 153,
    "updated_at": "2023-04-15T08:03:22.000Z",
    "language": "en",
    "available_translations": [
        "ar",
        "bg",
        "ca",
        "cs",
        "da",
        "de",
        "el",
        "en",
        "es",
        "fa",
        "fi",
        "fr",
        "he",
        "hr",
        "hu",
        "hy",
        "id",
        "it",
        "ja",
        "ka",
        "ko",
        "lt",
        "lv",
        "my",
        "nl",
        "pl",
        "pt",
        "ro",
        "ru",
        "sk",
        "sl",
        "sr",
        "sv",
        "th",
        "tr",
        "uk",
        "vi",
        "zh",
    ],
    "genres": ["action", "adventure", "science-fiction"],
    "certification": "PG-13",
}

{
    "title": "The Mandalorian",
    "year": 2019,
    "ids": {
        "trakt": 137178,
        "slug": "the-mandalorian",
        "tvdb": 361753,
        "imdb": "tt8111088",
        "tmdb": 82856,
        "tvrage": None,
    },
    "overview": "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
    "first_aired": "2019-11-12T08:00:00.000Z",
    "airs": {"day": "Friday", "time": "03:00", "timezone": "America/New_York"},
    "runtime": 40,
    "certification": "TV-14",
    "network": "Disney+",
    "country": "us",
    "trailer": "https://youtube.com/watch?v=2RVnrBLOBcI",
    "homepage": "https://www.disneyplus.com/series/the-mandalorian/3jLIGMDYINqD",
    "status": "returning series",
    "rating": 8.55223,
    "votes": 18045,
    "comment_count": 94,
    "updated_at": "2023-04-16T08:36:38.000Z",
    "language": "en",
    "available_translations": [
        "ar",
        "bg",
        "ca",
        "cs",
        "da",
        "de",
        "el",
        "en",
        "eo",
        "es",
        "et",
        "fa",
        "fi",
        "fr",
        "gl",
        "he",
        "hr",
        "hu",
        "it",
        "ja",
        "ka",
        "ko",
        "lt",
        "lv",
        "my",
        "nl",
        "no",
        "pl",
        "pt",
        "ro",
        "ru",
        "sk",
        "so",
        "sr",
        "sv",
        "th",
        "tr",
        "uk",
        "vi",
        "zh",
    ],
    "genres": ["fantasy", "science-fiction", "action", "adventure", "drama"],
    "aired_episodes": 23,
}
